### ISSUE TITLE
Properly validate network value provided to Porter via the CLI

### ISSUE THREAD

**Issue by andi2233i** [nucypher/nucypher-porter#2]
**Describe the Bug**
A clear and concise description of what the bug is, and what you expected to happen.
![image](https://user-images.githubusercontent.com/97090503/166937037-e4e14763-727a-4809-8e60-6612f76aa311.png)

**To Reproduce**
Steps to reproduce the behavior

**Traceback or Screenshots (Optional)**
If applicable, add the full error message / Traceback or upload screenshots to help explain your problem.

**System (please complete the following information):**
 - OS Version: ubuntu 18.3
 - Nucypher Version: 6.0.0
 - Ethereum Node Version:

**Comment by derekpierre** [comment]
Closed via #39 :

```
$ nucypher-porter run --domain mumbai --eth-endpoint <>
Usage: nucypher-porter run [OPTIONS]
Try 'nucypher-porter run --help' for help.

Error: Invalid value for '--domain': 'mumbai' is not a recognized domain. Valid options are: ['mainnet', 'lynx', 'tapir']
```
