### ISSUE TITLE
Remove use of `nucypher` dev installation once Prometheus issues are fixed

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher-porter#33]
#32 modified the Dockerfile to install a `nucypher` dev installation due to issues with the promtheus dependency in `nucypher` requiring a dev install.

Once that issue is wrapped up in `nucypher`, `nucypher-porter`'s Dockerfile should go back to using a `nucypher` regular (non-dev) installation.

(cc @KPrasch , @manumonti )

**Comment by manumonti** [comment]
@derekpierre IIRC, this is done. Could you confirm?

**Comment by derekpierre** [comment]
> @derekpierre IIRC, this is done. Could you confirm?

I don't think this will be done until PR https://github.com/nucypher/nucypher/pull/3223 is completed.

**Comment by derekpierre** [comment]
And Porter undoes - https://github.com/nucypher/nucypher-porter/pull/32/commits/46ba8b3e57c301305e3f9ab0c7d57fff97116dfd
