### ISSUE TITLE
Implement Alice revoke functionality for Porter

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher-porter#5]
Continuation of nucypher/nucypher#2703.

Implement `/revoke` once off-chain revoke is implemented; it is currently TBD after TMapConKFrags implementation (#2687 ) - see https://github.com/nucypher/nucypher/blob/main/nucypher/network/server.py#L278.

Original potential implementation for `/revoke` can be found here - https://github.com/nucypher/nucypher/issues/2666#issuecomment-844425997. However, this implementation may/may not need to be modified based on what is eventually done for TMapConKFrags off-chain revocation.

**Comment by derekpierre** [comment]
Depending on how revoke works, eg. purely on-chain and not off-chain communications with Ursula, then Porter may not need this functionality. 

Putting in project 6.2.0 for now, but could potentially be closed.

**Comment by KPrasch** [comment]
Revoke functionality has been subsumed by conditions based decryption.
